BurgerApp/Models/ErrorViewModel.cs
namespace BurgerApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BurgerApp/Controllers/BurgerController.cs
using BurgerApp.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BurgerApp.Controllers
{
    public class BurgerController : Controller
    {
        private readonly IBurgerService _burgerService;

        public BurgerController(IBurgerService burgerService)
        {
            _burgerService = burgerService;
        }

        public IActionResult Index()
        {
            var model = _burgerService.GetAllBurgers();
            return View(model);
        }
    }
}

BurgerApp/Controllers/HomeController.cs
using BurgerApp.DataAccess.Repositories;
using BurgerApp.DataAccess.Repositories.Interfaces;
using BurgerApp.Models;
using BurgerApp.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BurgerApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBurgerService _burgerService;

        public HomeController(ILogger<HomeController> logger, IBurgerService burgerService)
        {
            _logger = logger;
            _burgerService = burgerService;
        }

        public IActionResult Index()
        {
            var model = _burgerService.GetAllBurgersForHomePage();
            return View(model);
        }
    }
}

BurgerApp/Controllers/OrderController.cs
using BurgerApp.Services.Interfaces;
using BurgerApp.ViewModels.OrderViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BurgerApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IBurgerService _burgerService;
        private readonly IUserService _userService;

        public OrderController(IOrderService orderService, IBurgerService burgerService, IUserService userService)
        {
            _orderService = orderService;
            _burgerService = burgerService;
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AllOrders()
        {
            var model = _orderService.GetAllOrders();
            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = _orderService.GetOrderById(id);
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Users = _userService.GetUsersForDropdown();
            ViewBag.Burgers = _burgerService.GetBurgersForDropdown();
            var model = new OrderViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(OrderViewModel orderViewModel)
        {
            ViewBag.Users = _userService.GetUsersForDropdown();
            ViewBag.Burgers = _burgerService.GetBurgersForDropdown();

            if(ModelState.IsValid)
            {
                _orderService.CreateOrder(orderViewModel);
                return RedirectToAction("AllOrders");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Users = _userService.GetUsersForDropdown();
            ViewBag.Burgers = _burgerService.GetBurgersForDropdown();

            var model = _orderService.GetOrderForEdit(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(OrderViewModel orderViewModel)
        {
            ViewBag.Users = _userService.GetUsersForDropdown();
            ViewBag.Burgers = _burgerService.GetBurgersForDropdown();

            if (ModelState.IsValid)
            {
                _orderService.EditOrder(orderViewModel);
                return RedirectToAction("AllOrders");
            }
            return View();
        }

        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return View("BadRequest");
            }
            var model = _orderService.GetOrderById(id);
            return View(model);
        }

        public IActionResult ConfirmDelete(int id)
        {
            var model = _orderService.GetOrderById(id);
            _orderService.DeleteOrder(model.OrderId);
            return RedirectToAction("AllOrders");
        }
    }
}

BurgerApp/Views/Burger/Index.cshtml
@model List<BurgerListViewModel>

<partial name="~/Views/Shared/_BurgerCards.cshtml" for="@Model"></partial>

<a class="btn btn-primary my-3" asp-controller="Home" asp-action="index">Back</a>

BurgerApp/Views/Home/Index.cshtml
@model List<BurgerListViewModel>

<h1 class="display-1"> 7 FAST Food ® - Quality and tradition</h1>
<p class="lead mb-xxl-5">From 1987 we offer you the best fast food in Skopje</p>


<partial name="~/Views/Shared/_BurgerCards.cshtml" for="@Model"></partial>

<div class="d-flex justify-content-center">
    <a class="btn btn-primary my-3" asp-controller="Burger" asp-action="Index">More burgers</a>
</div>

BurgerApp/Views/Order/AllOrders.cshtml
@model List<OrderListViewModel>;

<h1>Admin Panel</h1>
<h3>Orders</h3>

<table class="table">
    <tr>
        <th scope="col" class="text-center">#</th>
        <th scope="col" class="text-center">User</th>
        <th scope="col" class="text-center">Burgers</th>
        <th scope="col" class="text-center">Details</th>
        <th scope="col" class="text-center">Edit</th>
        <th scope="col" class="text-center">Delete</th>
    </tr>

    <tbody>
        @foreach (var order in @Model)
        {
            <tr>
                <td scope="col" class="text-center">@order.OrderId</td>
                <td scope="col" class="text-center">@order.UserFullName</td>
                <td scope="col" class="text-center">
                    @String.Join(", ", order.Burgers)
                </td>
                <td scope="col" class="text-center"><a href="@Url.Action("details", "order")/@order.OrderId">More info</a></td>
                <td scope="col" class="text-center"><a href="@Url.Action("edit", "order")/@order.OrderId">Edit</a></td>
                <td scope="col" class="text-center"><a href="@Url.Action("delete", "order")/@order.OrderId">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary" asp-action="Index">Back</a>

BurgerApp/Views/Order/Create.cshtml
@model OrderViewModel

<h3>Create order:</h3>

@*<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" method="post">

            <div class="form-group my-3">
                <label asp-for="UserId" class="form-label"></label>
                <select class="form-control" asp-for="UserId" asp-items="@(new SelectList(ViewBag.Users, "Id", "FullName"))">
                    <option selected disabled>Select user</option>
                </select>
                <span class="text-danger" asp-validation-for="UserId"></span>
            </div>

            <div class="form-group my-3">
                <label asp-for="PaymentMethod" class="form-label"></label>
                <select class="form-control" asp-for="PaymentMethod" asp-items="Html.GetEnumSelectList<PaymentMethod>()">
                    <option selected disabled>Select Payment method</option>
                </select>
                <span class="text-danger" asp-validation-for="PaymentMethod"></span>
            </div>

            <div class="form-group my-3">
                <label class="form-label" asp-for="BurgerId">Choose burgers</label>
                <select class="form-control" asp-for="BurgerId" asp-items="@(new MultiSelectList(ViewBag.Burgers, "Id", "Name"))">
                    <option selected disabled>Select burgers</option>
                </select>
                <span class="text-danger" asp-validation-for="BurgerId"></span>
            </div>

            <button type="submit" class="btn btn-outline-success mt-4">Create</button>
        </form>
    </div>
</div>*@

<form asp-action="Create" asp-controller="Order" method="post">

    <div class="form-group my-3">
        <label class="form-label" asp-for="UserId">Choose User</label>
        <select class="form-control" asp-for="UserId" asp-items="@(new SelectList(ViewBag.Users, "Id", "FullName"))" required>
            <option selected disabled>Select user</option>
        </select>
        <span class="text-danger" asp-validation-for="UserId"></span>
    </div>

    <div class="form-group my-3">
        <label class="form-label" asp-for="PaymentMethod">Choose payment method</label>
        <select class="form-control" asp-for="PaymentMethod" asp-items="Html.GetEnumSelectList<PaymentMethod>()" required>
            <option selected disabled>Select Payment method</option>
        </select>
        <span class="text-danger" asp-validation-for="PaymentMethod"></span>
    </div>

    <div class="form-group my-3">
        <label class="form-label" asp-for="BurgerId">Choose burgers</label>
        <select class="form-control" asp-for="BurgerId" asp-items="@(new MultiSelectList(ViewBag.Burgers, "Id", "Name"))" required> 
            <option selected disabled>Select burgers</option>
        </select>
        <span class="text-danger" asp-validation-for="BurgerId"></span>
    </div>

    <button class="btn btn-outline-primary" type="submit">Create order</button>
</form>

BurgerApp/Views/Order/Delete.cshtml
@model OrderDetailsViewModel

<h3>Are you sure you want to delete order No. @Model.OrderId?</h3>

<a class="text-danger" asp-action="ConfirmDelete" asp-route-id="@Model.OrderId">Confirm</a>
<a class="text-primary" asp-action="AllOrders">Cancel</a>

BurgerApp/Views/Order/Details.cshtml
@model OrderDetailsViewModel

<table class="table">
    <tr>
        <th scope="col" class="align-middle text-center">#</th>
        <th scope="col" class="align-middle text-center">User</th>
        <th scope="col" class="align-middle text-center">Order Total price</th>
        <th scope="col" class="align-middle text-center">Address</th>
        <th scope="col" class="align-middle text-center">Full order</th>
        <th scope="col" class="align-middle text-center">Status</th>
    </tr>

    <tbody>
        <tr>
            <td scope="col" class="align-middle text-center">@Model.OrderId</td>
            <td scope="col" class="align-middle text-center">@Model.UserFullName</td>
            <td scope="col" class="align-middle text-center">@Model.TotalPrice MKD</td>
            <td scope="col" class="align-middle text-center">@Model.Address</td>
            <td scope="col" class="align-middle text-center">@String.Join(", ", Model.Burgers)</td>
            <td scope="col" class="align-middle text-center">@(Model.status ? "delivered" : "not delivered")</td>
        </tr>

    </tbody>
</table>

<a class="btn btn-primary" asp-action="AllOrders">Back</a>

BurgerApp/Views/Order/Edit.cshtml
@model OrderViewModel

<h3>Edit order:</h3>

<form asp-action="Edit" asp-controller="Order" method="post">

    <div class="form-group my-3">
        <label class="form-label" asp-for="UserId">Choose User</label>
        <select class="form-control" asp-for="UserId" asp-items="@(new SelectList(ViewBag.Users, "Id", "FullName"))">
        </select>
        <span class="text-danger" asp-validation-for="UserId"></span>
    </div>

    <div class="form-group my-3">
        <label class="form-label" asp-for="PaymentMethod">Choose payment method</label>
        <select class="form-control" asp-for="PaymentMethod" asp-items="Html.GetEnumSelectList<PaymentMethod>()"></select>
        <span class="text-danger" asp-validation-for="PaymentMethod"></span>
    </div>

    <div class="form-group my-3">
        <label class="form-label" asp-for="BurgerId">Choose burgers</label>
        <select class="form-control" asp-for="BurgerId" asp-items="@(new MultiSelectList(ViewBag.Burgers, "Id", "Name"))">
        </select>
        <span class="text-danger" asp-validation-for="BurgerId"></span>
    </div>

    <div class="form-group my-3">
        <label asp-for="IsDelivered" class="control-label"></label>
        <input type="checkbox" asp-for="IsDelivered" />
    </div>

    <button class="btn btn-outline-primary" type="submit">Edit order</button>
</form>

BurgerApp/Views/Order/Index.cshtml
<h1 class="display-1 text-center">Welcome to the orders menu</h1>

<h3>Pick one of the following options</h3>

<nav class="nav flex-column">
    <a class="nav-link" asp-action="AllOrders">
        1. View all orders
    </a>
    <a class="nav-link" asp-action="Create">
        2. Create new order
    </a>
</nav>

BurgerApp/Views/Shared/ExceptionPage.cshtml
<h2>An error occured, contact your administrator!</h2>

<a class="btn btn-outline-danger" asp-area="" asp-controller="Home" asp-action="Index">Back to Home</a>

BurgerApp/Views/Shared/_BurgerCards.cshtml
@model List<BurgerListViewModel>

<h3>Our menu:</h3>

<div class="card-group">
    @foreach (var burger in Model)
    {  
      <div class="card">
        <img class="card-img-top" src="@burger.Image" alt="Card image cap" height="250">
        <div class="card-body">
        <h5 class="card-title">@burger.Name</h5>
        <p class="card-text">@burger.Price MKD</p>
        <p class="card-text">Fries: @(burger.HasFries ? "Yes": "No" )</p>
    </div>
  </div>
    }
</div>

BurgerApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BurgerApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BurgerApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo.png" height="100px" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Burger" asp-action="Index">Burgers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BurgerApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>